#!/bin/zsh

# xprofile
[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

# for thinkpad
# xinput set-prop 'ETPS/2 Elantech TrackPoint' 'Device Enabled' 0
# xinput disable 'ETPS/2 Elantech Touchpad'

exec awesome
