customCommands:
  - key: "c"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen - commit tool"
    subprocess: true


git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
